#!/usr/bin/env node

/**
 * Single generator for all schema-driven artifacts.
 * Creates statusMapping.js, sizeConfig.js, and updates Dog.types.ts header
 *
 * Usage:
 *   npm run schema:gen          # Generate artifacts (regenerates even if in sync)
 *   npm run schema:check        # Check if artifacts are in sync with schema (fails if not)
 *
 * CI Usage:
 *   npm run schema:check        # Fail CI if artifacts are out of sync
 */

const fs = require('fs');
const path = require('path');
const { assertSchemaArtifactsInSync, generateSchemaChecksum, getSizeEnum } = require('./common/schemaArtifacts');

// Terminal statuses are now defined in the schema under x-terminal-statuses

const SCHEMA_PATH = 'common/schemas/dog.schema.json';
const STATUS_MAPPING_PATH = 'common/statusMapping.js';
const SIZE_CONFIG_PATH = 'common/sizeConfig.js';
const DOG_TYPES_PATH = 'services/webapp-react/src/types/Dog.types.ts';


function generateStatusMapping(schema, schemaContent) {
  const statusEnum = schema.properties.Status.enum;
  if (!statusEnum) {
    throw new Error('Status enum not found in schema');
  }

  const terminalStatuses = schema.properties.Status['x-terminal-statuses'] || [];
  const checksum = generateSchemaChecksum(schemaContent);
  const statusEntries = statusEnum.map(status => {
    const displayText = status.charAt(0) + status.slice(1).toLowerCase();
    const className = `status-${status.toLowerCase()}`;
    const isTerminal = terminalStatuses.includes(status);

    return `  '${status}': {
    text: '${displayText}',
    className: '${className}',
    isTerminal: ${isTerminal}
  }`;
  });

  return `/**
 * Shared status mapping constants for ETL and frontend.
 * AUTOGENERATED from ${SCHEMA_PATH} - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 *
 * CONTRACT: Status keys MUST exactly match ETL normalized statuses from schema.
 * If you add a new normalized status in schema, regenerate this file.
 */

export const STATUS_MAPPING = {
${statusEntries.join(',\n')}
};

export function getStatusDisplay(status) {
  return STATUS_MAPPING[status] || STATUS_MAPPING['UNKNOWN'];
}

export function isTerminalStatus(status) {
  return STATUS_MAPPING[status]?.isTerminal || false;
}

/**
 * Get all valid status keys for synchronization checks.
 * Tests can use this to ensure schema and UI stay in lockstep.
 */
export function getAllStatuses() {
  return Object.keys(STATUS_MAPPING);
}

// Note: Semantic flags (isInCustody, isAvailable, isHospice) are now computed by ETL
// and stored as IsInCustody, IsAvailableForAdoption, IsHospice in the schema.
// Use dogDerived.js helpers to access these flags from the schema fields.
`;
}

function generateSizeConfig(schema, schemaContent) {
  const sizeEnum = getSizeEnum();
  if (!sizeEnum || sizeEnum.length === 0) {
    throw new Error('Size enum not found in schema');
  }

  // Validate that schema enum order makes sense (should be ordered by size)
  const expectedOrder = ['Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'];
  if (JSON.stringify(sizeEnum) !== JSON.stringify(expectedOrder)) {
    throw new Error(
      `Schema Size enum order does not match expected SIZE_ORDER: ${JSON.stringify(sizeEnum)}\n` +
      `Expected: ${JSON.stringify(expectedOrder)}\n` +
      `Please update the schema to match the canonical size ordering.`
    );
  }

  const checksum = generateSchemaChecksum(schemaContent);
  const sizeOrder = sizeEnum.map(size => `'${size}'`).join(', ');

  return `/**
 * Shared size configuration constants for ETL and frontend.
 * AUTOGENERATED from ${SCHEMA_PATH} - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 */

export const SIZE_ORDER = [${sizeOrder}];

/**
 * Get the sort order index for a size string.
 * Returns a high index for unknown sizes to sort them last.
 */
export function getSizeSortIndex(size) {
  const index = SIZE_ORDER.indexOf(size);
  return index === -1 ? SIZE_ORDER.length : index;
}

/**
 * Assert that SIZE_ORDER matches the schema sizes for synchronization.
 * Call this during app startup in dev/test environments.
 */
export function assertSizeOrderMatchesSchema(schemaSizes) {
  if (!Array.isArray(schemaSizes)) return;
  if (schemaSizes.join('|') !== SIZE_ORDER.join('|')) {
    throw new Error(\`SIZE_ORDER out of sync with schema. Schema: [\${schemaSizes.join(', ')}], Config: [\${SIZE_ORDER.join(', ')}]\`);
  }
}

/**
 * Normalize a size string for display.
 * Returns the size if it's in SIZE_ORDER, otherwise returns 'UNKNOWN'.
 */
export function normalizeSizeForDisplay(size) {
  return SIZE_ORDER.includes(size) ? size : 'UNKNOWN';
}
`;
}


function updateDogTypesHeader(schemaContent) {
  const content = fs.readFileSync(DOG_TYPES_PATH, 'utf8');
  const lines = content.split('\n');

  // Find the end of the existing comment block
  let commentEndIndex = 0;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim() === '*/') {
      commentEndIndex = i;
      break;
    }
  }

  // Generate checksum for header
  const checksum = generateSchemaChecksum(schemaContent);

  // Replace everything up to and including the comment block
  const newHeader = `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript and ${path.basename(__filename)}.
 * DO NOT MODIFY IT BY HAND. Instead, modify ${SCHEMA_PATH},
 * then run json-schema-to-typescript and ${path.basename(__filename)} to regenerate this file.
 * Schema checksum: ${checksum}
 */`;

  // Replace from start up to comment end, then add the new header
  const restOfFile = lines.slice(commentEndIndex + 1).join('\n');
  const newContent = newHeader + '\n\n' + restOfFile;

  fs.writeFileSync(DOG_TYPES_PATH, newContent);
}

function main() {
  // Check if schema file exists before proceeding
  if (!fs.existsSync(SCHEMA_PATH)) {
    throw new Error(`Schema file not found: ${SCHEMA_PATH}`);
  }

  const checkOnly = process.argv.includes('--check');

  if (checkOnly) {
    console.log('Checking schema artifacts synchronization...');
    try {
      assertSchemaArtifactsInSync();
      console.log('✓ All schema artifacts are in sync');
    } catch (error) {
      console.error('❌ Schema artifacts out of sync:', error.message);
      console.error('\nTo fix this, run: npm run schema:gen');
      process.exit(1);
    }
    return;
  }

  // Read schema
  const schemaContent = fs.readFileSync(SCHEMA_PATH, 'utf8');
  const schema = JSON.parse(schemaContent);

  console.log('Generating schema artifacts...');

  // Generate status mapping
  const statusMapping = generateStatusMapping(schema, schemaContent);
  fs.writeFileSync(STATUS_MAPPING_PATH, statusMapping);
  console.log(`✓ Generated ${STATUS_MAPPING_PATH}`);

  // Generate size config
  const sizeConfig = generateSizeConfig(schema, schemaContent);
  fs.writeFileSync(SIZE_CONFIG_PATH, sizeConfig);
  console.log(`✓ Generated ${SIZE_CONFIG_PATH}`);

  // Update Dog.types.ts header
  updateDogTypesHeader(schemaContent);
  console.log(`✓ Updated ${DOG_TYPES_PATH} header`);

  console.log('Schema artifacts generation complete!');
}


if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error('Schema generation failed:', error.message);
    process.exit(1);
  }
}

module.exports = { generateStatusMapping, generateSizeConfig };
