"""
Dog data structure generated from common/schemas/dog.schema.json

Schema version: 1.3.0
AUTOGENERATED - DO NOT EDIT MANUALLY
Run: python3 scripts/generate_python_dog_types.py
"""

from dataclasses import dataclass
from typing import Dict, Any, List, Optional
from datetime import date


@dataclass
class Dog:
    """Dog record matching the canonical JSON schema."""

    Internal-ID: str = ...
    """ShelterLuv internal unique identifier - from ShelterLuv API field 'Internal-ID'"""

    ID: str = ...
    """ShelterLuv public animal ID - from ShelterLuv API field 'ID'"""

    Name: str = ...
    """Dog's name - from ShelterLuv API field 'Name'"""

    Breed: Optional[str] = None
    """Dog's breed - from ShelterLuv API field 'Breed'"""

    AgeYears: float = ...
    """Canonical age in years for sorting/filtering (e.g., 3.5 for 3 years 6 months) - computed from ShelterLuv age data"""

    AgeDisplay: str = ...
    """Human-readable age representation (e.g., '3 years', 'Adult', 'Senior') - computed from ShelterLuv age data"""

    Size: Optional[str] = None
    """Dog's size category - from ShelterLuv API field 'Size'. UNKNOWN indicates size could not be determined."""
    # Valid values: 'Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'

    Gender: Optional[str] = None
    """Dog's gender - from ShelterLuv API field 'Gender'"""
    # Valid values: 'Male', 'Female'

    Status: str = ...
    """Current status in shelter system - from ShelterLuv API field 'Status'. UNKNOWN indicates status could not be determined from ShelterLuv data."""
    # Valid values: 'AVAILABLE', 'ADOPTED', 'PENDING', 'HOLD', 'UNKNOWN'

    Description: Optional[str] = None
    """Dog's description/bio - from ShelterLuv API field 'Description'"""

    Photos: Optional[List[str]] = None
    """Array of photo URLs - from ShelterLuv API field 'Photos'"""

    CaseManager: Optional[str] = None
    """Assigned case manager name - scraped from ShelterLuv profile section"""

    MemosRawHTML: Optional[str] = None
    """Raw HTML content of all memos/notes - scraped from ShelterLuv memos page"""

    PersonalityNotes: str = ...
    """Personality and behavior notes extracted from MemosRawHTML - categorized by ETL based on keywords (personality, behavior, temperament, etc.)"""

    IntakeNotes: str = ...
    """Intake and background notes extracted from MemosRawHTML - categorized by ETL based on keywords (intake, background, history, etc.)"""

    MedicalNotes: str = ...
    """Medical notes extracted from MemosRawHTML - categorized by ETL based on keywords (medical, health, vet, treatment, etc.)"""

    AdoptionCategory: Optional[str] = None
    """Adoption category - scraped from ShelterLuv profile section"""

    MedicalCategory: Optional[str] = None
    """Medical category - scraped from ShelterLuv profile section"""

    BehaviorCategory: Optional[str] = None
    """Behavior category - scraped from ShelterLuv profile section"""

    FullAnimalProfile: Optional[str] = None
    """Full animal profile text - scraped from ShelterLuv profile section"""

    Treatments: Optional[List[Dict[str, Any]]] = None
    """Medical treatments history - structured from scraped data"""

    IntakeDate: Optional[str] = None
    """Date the dog was taken into custody - from ShelterLuv API field 'IntakeDate'"""

    Location: Optional[str] = None
    """Current location in shelter - from ShelterLuv API field 'Location'"""

    Stage: Optional[str] = None
    """Current stage in adoption process - from ShelterLuv API field 'Stage'"""

    Weight: Optional[str | float] = None
    """Dog's weight in pounds - from ShelterLuv API field 'Weight'"""

    FosterName: Optional[str] = None
    """Name of current foster parent - derived from ShelterLuv events and people data. ROLE RESTRICTED: closers/staff only"""

    FosterPhone: Optional[str] = None
    """Foster parent's phone number - derived from ShelterLuv people data. ROLE RESTRICTED: closers/staff only"""

    FosterEmail: Optional[str] = None
    """Foster parent's email address - derived from ShelterLuv people data. ROLE RESTRICTED: closers/staff only"""

    ScrapeError: Optional[str] = None
    """Error message if scraping dog details failed - shows in UI as warning"""

    IsInCustody: bool = ...
    """Dog is currently in Muttville's custody. True if dog is actively managed by Muttville (not adopted/returned). Computed from Status and ETL source data - all dogs from ShelterLuv 'In Custody' view are in custody."""

    IsAvailableForAdoption: bool = ...
    """Dog is actively available for public adoption. True only when Status is 'AVAILABLE'. Used by frontend to filter adoptable dogs."""

    IsHospice: bool = ...
    """Dog is in Muttville's hospice care program. Computed from MedicalCategory, Stage, event history, and hospice-related keywords in metadata."""

    IsEventDog: bool = ...
    """Dog participates in public events/outreach. Computed from event history, AdoptionCategory, BehaviorCategory, and event-related keywords in description/personality notes."""

# Status enum values
DOG_STATUSES = [
    "AVAILABLE",
    "ADOPTED",
    "PENDING",
    "HOLD",
    "UNKNOWN",
]

# Size enum values
DOG_SIZES = [
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "UNKNOWN",
]

# Gender enum values
DOG_GENDERS = [
    "Male",
    "Female",
]