/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript and schemaArtifactsCli.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify common/schemas/dog.schema.json,
 * then run json-schema-to-typescript and schemaArtifactsCli.js to regenerate this file.
 * Schema checksum: 65ad864d
 */




/**
 * Schema for dog data collected from ShelterLuv. Frontend renders: Name, Age, Size, Gender, Status, Photos, Description, CaseManager, AdoptionCategory, MedicalCategory, BehaviorCategory. Supports role-based access to foster contact information and structured memo tabs.
 */
export interface Dog {
  /**
   * [API] ShelterLuv internal unique identifier - from ShelterLuv API field 'Internal-ID'
   */
  "Internal-ID": string;
  /**
   * [API] ShelterLuv public animal ID - from ShelterLuv API field 'ID'
   */
  ID: string;
  /**
   * [API] Dog's name - from ShelterLuv API field 'Name'
   */
  Name: string;
  /**
   * [API] Dog's breed - from ShelterLuv API field 'Breed'
   */
  Breed?: string;
  /**
   * [DERIVED] Canonical age in years for sorting/filtering (e.g., 3.5 for 3 years 6 months) - computed from ShelterLuv age data
   */
  AgeYears: number;
  /**
   * [DERIVED] Human-readable age representation (e.g., '3 years', 'Adult', 'Senior') - computed from ShelterLuv age data
   */
  AgeDisplay: string;
  /**
   * [API] Dog's size category - from ShelterLuv API field 'Size'. UNKNOWN indicates size could not be determined.
   */
  Size?: "Small" | "Medium" | "Large" | "X-Large" | "UNKNOWN";
  /**
   * [API] Dog's gender - from ShelterLuv API field 'Gender'
   */
  Gender?: "Male" | "Female";
  /**
   * [API] Current status in shelter system - from ShelterLuv API field 'Status'. UNKNOWN indicates status could not be determined from ShelterLuv data.
   */
  Status: "AVAILABLE" | "ADOPTED" | "PENDING" | "HOLD" | "UNKNOWN";
  /**
   * [API] Dog's description/bio - from ShelterLuv API field 'Description'
   */
  Description?: string;
  /**
   * [API] Array of photo URLs - from ShelterLuv API field 'Photos'
   */
  Photos?: string[];
  /**
   * [SCRAPED] Assigned case manager name - scraped from ShelterLuv profile section
   */
  CaseManager?: string;
  /**
   * [SCRAPED] Raw HTML content of all memos/notes - scraped from ShelterLuv memos page
   */
  MemosRawHTML?: string;
  /**
   * [DERIVED] Personality and behavior notes extracted from MemosRawHTML - categorized by ETL based on keywords (personality, behavior, temperament, etc.)
   */
  PersonalityNotes: string;
  /**
   * [DERIVED] Intake and background notes extracted from MemosRawHTML - categorized by ETL based on keywords (intake, background, history, etc.)
   */
  IntakeNotes: string;
  /**
   * [DERIVED] Medical notes extracted from MemosRawHTML - categorized by ETL based on keywords (medical, health, vet, treatment, etc.)
   */
  MedicalNotes: string;
  /**
   * [SCRAPED] Adoption category - scraped from ShelterLuv profile section
   */
  AdoptionCategory?: string;
  /**
   * [SCRAPED] Medical category - scraped from ShelterLuv profile section
   */
  MedicalCategory?: string;
  /**
   * [SCRAPED] Behavior category - scraped from ShelterLuv profile section
   */
  BehaviorCategory?: string;
  /**
   * [SCRAPED] Full animal profile text - scraped from ShelterLuv profile section
   */
  FullAnimalProfile?: string;
  /**
   * [DERIVED] Medical treatments history - structured from scraped data
   */
  Treatments?: {
    date?: string;
    treatment?: string;
    notes?: string;
    [k: string]: unknown;
  }[];
  /**
   * [API] Date the dog was taken into custody - from ShelterLuv API field 'IntakeDate'
   */
  IntakeDate?: string;
  /**
   * [API] Current location in shelter - from ShelterLuv API field 'Location'
   */
  Location?: string;
  /**
   * [API] Current stage in adoption process - from ShelterLuv API field 'Stage'
   */
  Stage?: string;
  /**
   * [API] Dog's weight in pounds - from ShelterLuv API field 'Weight'
   */
  Weight?: string | number;
  /**
   * [DERIVED] Name of current foster parent - derived from ShelterLuv events and people data. ROLE RESTRICTED: closers/staff only
   */
  FosterName?: string;
  /**
   * [DERIVED] Foster parent's phone number - derived from ShelterLuv people data. ROLE RESTRICTED: closers/staff only
   */
  FosterPhone?: string;
  /**
   * [DERIVED] Foster parent's email address - derived from ShelterLuv people data. ROLE RESTRICTED: closers/staff only
   */
  FosterEmail?: string;
  /**
   * [DERIVED] Error message if scraping dog details failed - shows in UI as warning
   */
  ScrapeError?: string;
  /**
   * [DERIVED] Dog is currently in Muttville's custody. True if dog is actively managed by Muttville (not adopted/returned). Computed from Status and ETL source data - all dogs from ShelterLuv 'In Custody' view are in custody.
   */
  IsInCustody: boolean;
  /**
   * [DERIVED] Dog is actively available for public adoption. True only when Status is 'AVAILABLE'. Used by frontend to filter adoptable dogs.
   */
  IsAvailableForAdoption: boolean;
  /**
   * [DERIVED] Dog is in Muttville's hospice care program. Computed from MedicalCategory, Stage, event history, and hospice-related keywords in metadata.
   */
  IsHospice: boolean;
  /**
   * [DERIVED] Dog participates in public events/outreach. Computed from event history, AdoptionCategory, BehaviorCategory, and event-related keywords in description/personality notes.
   */
  IsEventDog: boolean;
  /**
   * [SCRAPED] Attribute tags for this dog - scraped from ShelterLuv Attributes tab (e.g., 'Cat-friendly', 'Potty trained'). Used for filtering and display in UI.
   */
  Attributes?: string[];
}
