/**
 * TypeScript types for dog data.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: b976bee0
 */

export interface Dog {
  Internal-ID: string;
  ID: string;
  Name: string;
  Breed?: string;
  AgeYears: number;
  AgeDisplay: string;
  Size?: 'Small' | 'Medium' | 'Large' | 'X-Large' | 'UNKNOWN';
  Gender?: 'Male' | 'Female';
  Status: 'AVAILABLE' | 'ADOPTED' | 'PENDING' | 'HOLD' | 'UNKNOWN';
  Description?: string;
  Photos?: string[];
  CaseManager?: string;
  MemosRawHTML?: string;
  PersonalityNotes: string;
  IntakeNotes: string;
  MedicalNotes: string;
  MedicalHistory?: {
    vaccinations: {
    name: string;
    date: string;
    status: string;
    lot_number: string;
    expiration_date: string;
    rabies_tag_number: string;
    source: string;
    route: string;
    site: string;
    vaccinated_by: string;
  }[];
    treatments_due: {
    name: string;
    dosage: string;
    frequency: string;
    due_date: string;
  }[];
    treatment_history: {
    name: string;
    dosage: string;
    frequency: string;
    start_date: string;
    end_date: string;
    notes: string;
  }[];
    active_diagnoses: {
    condition: string;
    diagnosed_date: string;
    notes: string;
  }[];
    resolved_diagnoses: {
    condition: string;
    diagnosed_date: string;
    resolved_date: string;
    notes: string;
  }[];
    diagnostic_tests: {
    test_type: string;
    test_name: string;
    date: string;
    results: string;
    results_detail: string;
    test_by: string;
    veterinarian: string;
    notes: string;
  }[];
    physical_exams: {
    exam_type: string;
    date_time: string;
    details: string;
  }[];
    procedures_surgeries: {
    procedure_type: string;
    date_time: string;
    details: string;
  }[];
  };
  AdoptionCategory?: string;
  MedicalCategory?: string;
  BehaviorCategory?: string;
  VolunteerCategory?: string;
  FullAnimalProfile?: string;
  Treatments?: {
    date: string;
    treatment: string;
    notes: string;
  }[];
  IntakeDate?: string;
  Location?: string;
  Stage?: string;
  Weight?: string | number;
  FosterName?: string;
  FosterPhone?: string;
  FosterEmail?: string;
  ScrapeError?: string;
  IsInCustody: boolean;
  IsAvailableForAdoption: boolean;
  IsHospice: boolean;
  IsEventDog: boolean;
  Attributes?: string[];
  BehavioralAttributes?: string[];
  PhysicalAttributes?: string[];
  Species?: string;
  Color?: string;
  Pattern?: string;
  DistinguishingMarks?: string;
  AdoptionPrice?: string;
  MicrochipNumber?: string;
  MicrochipIssuer?: string;
  MicrochipImplantDate?: string;
  AlteredBeforeArrival?: string;
  AlteredInCare?: string;
  AgeGroup?: string;
  EstBirthdate?: string;
  IntakeType?: string;
  IntakeSubtype?: string;
  OutcomeType?: string;
  OutcomeSubtype?: string;
  AsilomarIntake?: string;
  AsilomarOutcome?: string;
  ConditionAtIntake?: string;
  JurisdictionIntake?: string;
  JurisdictionOutcome?: string;
  RabiesTagNumber?: string;
  EventHistory?: {
    event_type: string;
    date: string;
    associated_person: string;
    details: string;
    status_change: string;
  }[];
  WeightHistory?: {
    weight: string;
    date: string;
    unit: 'kg' | 'lbs';
  }[];
  CategoryHistory?: {
    category: string;
    date: string;
    assigned_by: string;
    details: string;
  }[];
  BehavioralAssessments?: {
    assessment_type: string;
    date: string;
    assessor: string;
    results: string;
    recommendations: string;
  }[];
  CompatibilityWarnings?: {
    warning_type: string;
    severity: 'Unknown' | 'Caution' | 'Not Recommended';
    details: string;
    date_noted: string;
  }[];
  AttachedDocuments?: {
    filename: string;
    file_type: 'PDF' | 'Image' | 'Document' | 'Other';
    upload_date: string;
    url: string;
    description: string;
  }[];
  PreviousShelterId?: string;
  PreviousShelterType?: string;
  PreviousShelterIssuer?: string;
  Disclaimers?: {
    title: string;
    content: string;
    category: 'compatibility' | 'behavior' | 'medical' | 'housing' | 'other';
  }[];
  WebsiteMemo?: {
    author: string;
    date: string;
    content: string;
  };
  MicrochipInfo?: {
    number: string;
    issued_date: string;
    issuer: string;
  };
  RabiesTag?: {
    number: string;
  };
  VaccinationHistory?: {
    vaccine: string;
    date: string;
    expiration_date: string;
    route: string;
    site: string;
    lot_number: string;
    status: 'Completed' | 'Scheduled' | 'Overdue';
  }[];
  TreatmentsDue?: {
    treatment: string;
    dosage: string;
    frequency: string;
    due_date: string;
    status: 'Overdue' | 'Due' | 'Completed';
  }[];
  TreatmentHistory?: {
    treatment: string;
    dosage: string;
    frequency: string;
    start_date: string;
    end_date: string;
    status: 'Completed' | 'In Progress' | 'Cancelled';
    notes: string;
    veterinarian: string;
  }[];
  Diagnoses?: {
    condition: string;
    category: 'Dental/Periodontal Disease' | 'Cardiovascular' | 'Skin' | 'Other';
    status: 'Active' | 'Resolved' | 'Diagnosed';
    diagnosed_date: string;
    resolved_date: string;
    description: string;
    veterinarian: string;
  }[];
  DiagnosticTests?: {
    test_type: string;
    date: string;
    results: string;
    status: 'Completed' | 'Pending' | 'Scheduled';
    veterinarian: string;
    notes: string;
  }[];
  PhysicalExams?: {
    exam_type: string;
    date: string;
    veterinarian: string;
    clinic: string;
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
  }[];
  Procedures?: {
    procedure: string;
    date: string;
    surgeon: string;
    clinic: string;
    notes: string;
    status: 'Completed' | 'Scheduled' | 'Cancelled';
  }[];
  MedicalMemos?: {
    date: string;
    author: string;
    content: string;
  }[];
}

/**
 * Type guard to check if a value is a valid Dog object.
 * @param value - The value to check
 * @returns True if the value conforms to the Dog interface
 */
export function isDog(value: any): value is Dog {
  return typeof value === 'object' && value !== null &&
    typeof value['Internal-ID'] === 'string' &&
    typeof value['ID'] === 'string' &&
    typeof value['Name'] === 'string';
}
