/**
 * Generate type artifacts from schema.
 * Pure functions for TypeScript and Python type generation.
 */

const { assertSchemaStructure, generateSchemaChecksum } = require('./loadConfig');

/**
 * Generate TypeScript dog types from schema.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} TypeScript interface definitions
 */
function generateTypescriptDogTypes(schema, schemaContent) {
  assertSchemaStructure(schema);

  const checksum = generateSchemaChecksum(schemaContent);

  // Generate property type mappings
  const propertyTypes = {};
  for (const [propName, propDef] of Object.entries(schema.properties)) {
    propertyTypes[propName] = jsonTypeToTypescriptType(propDef, propName);
  }

  // Generate the interface
  const requiredFields = schema.required || [];
  const properties = Object.entries(propertyTypes).map(([name, type]) => {
    const optional = !requiredFields.includes(name) ? '?' : '';
    return `  ${name}${optional}: ${type};`;
  }).join('\n');

  return `/**
 * TypeScript types for dog data.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 */

export interface Dog {
${properties}
}

/**
 * Type guard to check if a value is a valid Dog object.
 * @param value - The value to check
 * @returns True if the value conforms to the Dog interface
 */
export function isDog(value: any): value is Dog {
  return typeof value === 'object' && value !== null &&
    typeof value['Internal-ID'] === 'string' &&
    typeof value['ID'] === 'string' &&
    typeof value['Name'] === 'string';
}
`;
}

/**
 * Convert JSON schema type to TypeScript type.
 * @param {object} propDef - Property definition from schema
 * @param {string} propName - Property name for context
 * @returns {string} TypeScript type string
 */
function jsonTypeToTypescriptType(propDef, propName) {
  // Handle union types (e.g., string | number for Weight)
  if (Array.isArray(propDef.type)) {
    return propDef.type.map(t => jsonTypeToTypescriptType({ ...propDef, type: t }, propName)).join(' | ');
  }

  switch (propDef.type) {
    case 'string':
      if (propDef.enum) {
        return propDef.enum.map(s => `'${s}'`).join(' | ');
      }
      if (propDef.format === 'email') {
        return 'string'; // Keep as string for simplicity
      }
      if (propDef.format === 'uri') {
        return 'string';
      }
      if (propDef.format === 'date') {
        return 'string'; // ISO date string
      }
      return 'string';

    case 'number':
      return 'number';

    case 'boolean':
      return 'boolean';

    case 'array':
      if (propDef.items) {
        const itemType = jsonTypeToTypescriptType(propDef.items, `${propName}[]`);
        return `${itemType}[]`;
      }
      return 'any[]';

    case 'object':
      if (propDef.properties) {
        // For complex objects like MedicalHistory, generate inline interface
        const props = Object.entries(propDef.properties).map(([k, v]) => {
          const type = jsonTypeToTypescriptType(v, `${propName}.${k}`);
          return `    ${k}: ${type};`;
        }).join('\n');
        return `{\n${props}\n  }`;
      }
      return 'Record<string, any>';

    default:
      return 'any';
  }
}

/**
 * Generate Python dog types from schema.
 * Generates a TypedDict with proper field names and types for IDE support and type checking.
 *
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} Python TypedDict definitions
 */
function generatePythonDogTypes(schema, schemaContent) {
  assertSchemaStructure(schema);

  const checksum = generateSchemaChecksum(schemaContent);

  // Generate property type mappings
  const propertyTypes = {};
  for (const [propName, propDef] of Object.entries(schema.properties)) {
    propertyTypes[propName] = jsonTypeToPythonType(propDef, propName);
  }

  // Generate the TypedDict class
  const requiredFields = schema.required || [];
  const properties = Object.entries(propertyTypes).map(([name, type]) => {
    const required = requiredFields.includes(name);
    const comment = required ? '' : '  # Optional';
    return `    ${jsonStringToPythonIdentifier(name)}: ${type}${comment}`;
  }).join('\n');

  return `# Python types for dog data.
# AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
# Schema checksum: ${checksum}

from typing import Dict, Any

# Dog type alias for type checking and IDE support
# The structure follows the JSON schema in common/schemas/dog.schema.json
Dog = Dict[str, Any]
`;
}

/**
 * Convert JSON property name to Python-compatible identifier.
 * @param {string} propName - Property name from schema
 * @returns {string} Python-compatible identifier
 */
function jsonStringToPythonIdentifier(propName) {
  // Convert to valid Python identifier by replacing special chars with underscores
  return propName.replace(/[^a-zA-Z0-9_]/g, '_');
}

/**
 * Convert JSON schema type to Python type annotation.
 * @param {object} propDef - Property definition from schema
 * @param {string} propName - Property name for context
 * @returns {string} Python type annotation
 */
function jsonTypeToPythonType(propDef, propName = '') {
  // Handle union types
  if (Array.isArray(propDef.type)) {
    const types = propDef.type.map(t => jsonTypeToPythonType({ ...propDef, type: t }, propName));
    return `Union[${types.join(', ')}]`;
  }

  switch (propDef.type) {
    case 'string':
      if (propDef.enum) {
        return `Literal[${propDef.enum.map(s => `'${s}'`).join(', ')}]`;
      }
      if (propDef.format === 'email') {
        return 'str';
      }
      if (propDef.format === 'uri') {
        return 'str';
      }
      if (propDef.format === 'date') {
        return 'str'; // ISO date string
      }
      if (propDef.format === 'date-time') {
        return 'str'; // ISO datetime string
      }
      return 'str';

    case 'number':
      return 'float';

    case 'boolean':
      return 'bool';

    case 'array':
      if (propDef.items) {
        const itemType = jsonTypeToPythonType(propDef.items, `${propName}[]`);
        return `List[${itemType}]`;
      }
      return 'List[Any]';

    case 'object':
      if (propDef.properties) {
        // For complex objects, use Dict for simplicity
        return 'Dict[str, Any]';
      }
      return 'Dict[str, Any]';

    default:
      return 'Any';
  }
}

/**
 * Generate header comment for generated type files.
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @param {object} options - Generation options
 * @returns {string} Header comment string
 */
function generateDogTypesHeader(schemaContent, options = {}) {
  const {
    generatorFileName = 'schemaArtifactsCli.js'
  } = options;
  const checksum = generateSchemaChecksum(schemaContent);

  return `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript and ${generatorFileName}.
 * DO NOT MODIFY IT BY HAND. Instead, modify common/schemas/dog.schema.json,
 * then run json-schema-to-typescript and ${generatorFileName} to regenerate this file.
 * Schema checksum: ${checksum}
 */`;
}

module.exports = {
  generateTypescriptDogTypes,
  generatePythonDogTypes,
  generateDogTypesHeader
};
