/**
 * Generate config artifacts from config data.
 * Pure functions for JavaScript and Python config artifact generation.
 */

const { generateConfigChecksum } = require('./loadConfig');

/**
 * Normalize config data into standardized artifact structure.
 * @param {object} config - Parsed config object
 * @param {string} configContent - Raw config file content (for checksum)
 * @returns {object} Normalized artifact object
 */
function normalizeConfig(config, configContent) {
  const checksum = generateConfigChecksum(configContent);

  // Build normalized mappings
  const profileSafetyMap = {};
  const projectSafetyMap = {};

  for (const profileName of Object.keys(config.python_env_profiles || {})) {
    const profileConfig = config.python_env_profiles[profileName];
    const isSafe = config.safe_profiles.includes(profileName);

    profileSafetyMap[profileName] = {
      gcp_project: profileConfig.gcp_project,
      is_safe: isSafe
    };

    const projectId = profileConfig.gcp_project;
    projectSafetyMap[projectId] = {
      is_safe: isSafe
    };
  }

  return {
    checksum,
    generated_at: new Date().toISOString(),
    generator: "writers.js",
    env_profiles: config.env_profiles,
    safe_profiles: config.safe_profiles,
    roles: config.roles,
    profile_safety_map: profileSafetyMap,
    project_safety_map: projectSafetyMap
  };
}

/**
 * Generate JavaScript config artifact from config.
 * @param {object} config - Parsed config object
 * @param {string} configContent - Raw config file content (for checksum)
 * @returns {string} JavaScript module source code
 */
function generateConfigArtifact(config, configContent) {
  const artifact = normalizeConfig(config, configContent);

  return `/**
 * Unified config artifact for cross-language consumption.
 * AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
 * Config checksum: ${artifact.checksum}
 *
 * This artifact contains normalized profile mappings and safety rules
 * that both JavaScript and Python code can consume without duplication.
 *
 * Business logic helpers are in configArtifactHelpers.js
 */

const CONFIG_ARTIFACT = ${JSON.stringify(artifact, null, 2)};

module.exports = {
  CONFIG_ARTIFACT
};
`;
}

/**
 * Generate Python config artifact from config.
 * @param {object} config - Parsed config object
 * @param {string} configContent - Raw config file content (for checksum)
 * @returns {string} Python module source code
 */
function generatePythonConfigArtifactFromConfig(config, configContent) {
  const artifact = normalizeConfig(config, configContent);

  // Convert JavaScript JSON to Python literals
  let pythonJson = JSON.stringify(artifact, null, 2);
  pythonJson = pythonJson.replace(/true/g, 'True').replace(/false/g, 'False').replace(/null/g, 'None');

  return `# Python config artifact.
# AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
# Config checksum: ${artifact.checksum}

import json
from typing import Dict, Any

CONFIG_ARTIFACT = ${pythonJson}

def get_env_profiles() -> Dict[str, Any]:
    return CONFIG_ARTIFACT["env_profiles"]

def get_safe_profiles() -> list:
    return CONFIG_ARTIFACT["safe_profiles"]

def get_roles() -> list:
    return CONFIG_ARTIFACT["roles"]

def get_profile_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["profile_safety_map"]

def get_project_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["project_safety_map"]

def is_profile_safe(profile_name: str) -> bool:
    return CONFIG_ARTIFACT["profile_safety_map"].get(profile_name, {}).get("is_safe", False)

def is_project_safe(project_id: str) -> bool:
    return CONFIG_ARTIFACT["project_safety_map"].get(project_id, {}).get("is_safe", False)
`;
}

module.exports = {
  normalizeConfig,
  generateConfigArtifact,
  generatePythonConfigArtifact: generatePythonConfigArtifactFromConfig, // alias for backward compatibility
  generatePythonConfigArtifactFromConfig
};
