/**
 * Generate config artifacts from config data.
 * Pure functions for JavaScript and Python config artifact generation.
 */

const { generateConfigChecksum } = require('./loadConfig');

/**
 * Generate JavaScript config artifact from config.
 * @param {object} config - Parsed config object
 * @param {string} configContent - Raw config file content (for checksum)
 * @returns {string} JavaScript module source code
 */
function generateConfigArtifact(config, configContent) {
  const checksum = generateConfigChecksum(configContent);

  // Build normalized mappings
  const profileSafetyMap = {};
  const projectSafetyMap = {};

  for (const profileName of Object.keys(config.python_env_profiles || {})) {
    const profileConfig = config.python_env_profiles[profileName];
    const isSafe = config.safe_profiles.includes(profileName);

    profileSafetyMap[profileName] = {
      gcp_project: profileConfig.gcp_project,
      is_safe: isSafe
    };

    const projectId = profileConfig.gcp_project;
    projectSafetyMap[projectId] = {
      is_safe: isSafe
    };
  }

  const artifact = {
    checksum,
    generated_at: new Date().toISOString(),
    generator: "writers.js",
    env_profiles: config.env_profiles,
    safe_profiles: config.safe_profiles,
    roles: config.roles,
    profile_safety_map: profileSafetyMap,
    project_safety_map: projectSafetyMap
  };

  return `/**
 * Unified config artifact for cross-language consumption.
 * AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
 * Config checksum: ${checksum}
 *
 * This artifact contains normalized profile mappings and safety rules
 * that both JavaScript and Python code can consume without duplication.
 */

const CONFIG_ARTIFACT = ${JSON.stringify(artifact, null, 2)};

// Convenience accessors
function getEnvProfiles() {
  return CONFIG_ARTIFACT.env_profiles;
}

function getSafeProfiles() {
  return CONFIG_ARTIFACT.safe_profiles;
}

function getRoles() {
  return CONFIG_ARTIFACT.roles;
}

function getProfileSafetyMap() {
  return CONFIG_ARTIFACT.profile_safety_map;
}

function getProjectSafetyMap() {
  return CONFIG_ARTIFACT.project_safety_map;
}

function isProfileSafe(profileName) {
  return CONFIG_ARTIFACT.profile_safety_map[profileName]?.is_safe || false;
}

function isProjectSafe(projectId) {
  return CONFIG_ARTIFACT.project_safety_map[projectId]?.is_safe || false;
}

module.exports = {
  CONFIG_ARTIFACT,
  getEnvProfiles,
  getSafeProfiles,
  getRoles,
  getProfileSafetyMap,
  getProjectSafetyMap,
  isProfileSafe,
  isProjectSafe
};
`;
}

/**
 * Generate Python config artifact from config.
 * @param {object} config - Parsed config object
 * @param {string} configContent - Raw config file content (for checksum)
 * @returns {string} Python module source code
 */
function generatePythonConfigArtifactFromConfig(config, configContent) {
  const checksum = generateConfigChecksum(configContent);

  // Build normalized mappings
  const profileSafetyMap = {};
  const projectSafetyMap = {};

  for (const profileName of Object.keys(config.python_env_profiles || {})) {
    const profileConfig = config.python_env_profiles[profileName];
    const isSafe = config.safe_profiles.includes(profileName);

    profileSafetyMap[profileName] = {
      gcp_project: profileConfig.gcp_project,
      is_safe: isSafe
    };

    const projectId = profileConfig.gcp_project;
    projectSafetyMap[projectId] = {
      is_safe: isSafe
    };
  }

  const artifact = {
    checksum,
    generated_at: new Date().toISOString(),
    generator: "writers.js",
    env_profiles: config.env_profiles,
    safe_profiles: config.safe_profiles,
    roles: config.roles,
    profile_safety_map: profileSafetyMap,
    project_safety_map: projectSafetyMap
  };

  return `# Python config artifact.
# AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
# Config checksum: ${checksum}

import json
from typing import Dict, Any

CONFIG_ARTIFACT = ${JSON.stringify(artifact, null, 2)}

def get_env_profiles() -> Dict[str, Any]:
    return CONFIG_ARTIFACT["env_profiles"]

def get_safe_profiles() -> list:
    return CONFIG_ARTIFACT["safe_profiles"]

def get_roles() -> list:
    return CONFIG_ARTIFACT["roles"]

def get_profile_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["profile_safety_map"]

def get_project_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["project_safety_map"]
`;
}

module.exports = {
  generateConfigArtifact,
  generatePythonConfigArtifact: generatePythonConfigArtifactFromConfig, // alias for backward compatibility
  generatePythonConfigArtifactFromConfig
};
