/**
 * Generate dog-related artifacts from schema.
 * Pure functions for status mapping and size configuration.
 */

const { assertSchemaStructure, generateSchemaChecksum } = require('./loadConfig');

/**
 * Generate status mapping ESM module content from schema.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} ESM module source code
 */
function generateStatusMapping(schema, schemaContent) {
  assertSchemaStructure(schema);

  const terminalStatuses = schema.properties.Status['x-terminal-statuses'];
  const checksum = generateSchemaChecksum(schemaContent);
  const statusEntries = schema.properties.Status.enum.map((status) => {
    const displayText = status.charAt(0) + status.slice(1).toLowerCase();
    const className = `status-${status.toLowerCase()}`;
    const isTerminal = terminalStatuses.includes(status);

    return `  '${status}': {
    text: '${displayText}',
    className: '${className}',
    isTerminal: ${isTerminal}
  }`;
  });

  return `/**
 * Shared status mapping constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 *
 * CONTRACT: Status keys MUST exactly match ETL normalized statuses from schema.
 * If you add a new normalized status in schema, regenerate this file.
 */

export const STATUS_MAPPING = {
${statusEntries.join(',\n')}
};

export function getStatusDisplay(status) {
  return STATUS_MAPPING[status] || STATUS_MAPPING['UNKNOWN'];
}

export function isTerminalStatus(status) {
  const mapping = STATUS_MAPPING[status];
  return mapping ? mapping.isTerminal : false;
}

export function getAllStatuses() {
  return Object.keys(STATUS_MAPPING);
}
`;
}

/**
 * Generate size config ESM module content from schema.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} ESM module source code
 */
function generateSizeConfig(schema, schemaContent) {
  assertSchemaStructure(schema);

  const checksum = generateSchemaChecksum(schemaContent);
  const schemaSizes = schema.properties.Size.enum;

  return `/**
 * Shared size configuration constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 *
 * CONTRACT: Size order MUST exactly match schema enum order.
 * If you change size enum in schema, regenerate this file.
 */

export const SIZE_ORDER = [${schemaSizes.map(s => `'${s}'`).join(', ')}];

export function getSizeSortIndex(size) {
  const index = SIZE_ORDER.indexOf(size);
  return index === -1 ? SIZE_ORDER.length - 1 : index; // UNKNOWN sorts last
}

export function assertSizeOrderMatchesSchema(schemaSizes) {
  const expected = SIZE_ORDER.filter(size => size !== 'UNKNOWN');
  if (JSON.stringify(expected) !== JSON.stringify(schemaSizes)) {
    throw new Error(\`Size order mismatch: expected \${expected.join(', ')}, got \${schemaSizes.join(', ')}\`);
  }
}

export function normalizeSizeForDisplay(size) {
  return size || 'UNKNOWN';
}
`;
}

module.exports = {
  generateStatusMapping,
  generateSizeConfig
};
