/**
 * Schema transformation utilities.
 * Orchestrator for generating all artifacts from schema and config data.
 */

const { generateStatusMapping, generateSizeConfig } = require('./generateDogArtifacts');
const { generateTypescriptDogTypes, generatePythonDogTypes, generateDogTypesHeader } = require('./generateTypes');
const { generateConfigArtifact, generatePythonConfigArtifact } = require('./generateConfigArtifacts');

// Stub functions for schema artifacts - TODO: implement properly
function generateSchemaArtifact(schema, schemaContent, options = {}) {
  const { generateSchemaChecksum } = require('./loadConfig');
  const { enumerateStatuses, enumerateSizes, enumerateRequiredFields, enumerateTerminalStatuses, getSizeOrdering, extractSchemaMetadata } = require('./loadConfig');

  const checksum = generateSchemaChecksum(schemaContent);
  const metadata = extractSchemaMetadata(schema);

  const artifact = {
    checksum,
    generated_at: new Date().toISOString(),
    generator: options.generatorFileName || 'transformSchema.js',
    version: schema.version || '1.0.0',
    title: schema.title || 'Untitled',
    requiredFields: enumerateRequiredFields(schema),
    statuses: enumerateStatuses(schema),
    sizes: enumerateSizes(schema),
    terminalStatuses: enumerateTerminalStatuses(schema),
    sizeOrdering: getSizeOrdering(schema),
    ...metadata
  };

  return `/**
 * Comprehensive schema artifact with all validation rules and metadata.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 *
 * This artifact contains all schema-derived constants, enums, and validation rules
 * used throughout the application for consistent data handling.
 */

const SCHEMA_ARTIFACT = ${JSON.stringify(artifact, null, 2)};

module.exports = {
  SCHEMA_ARTIFACT
};
`;
}

function generatePythonSchemaArtifact(schema, schemaContent, options = {}) {
  const { generateSchemaChecksum } = require('./loadConfig');
  const { enumerateStatuses, enumerateSizes, enumerateRequiredFields, enumerateTerminalStatuses, getSizeOrdering, extractSchemaMetadata } = require('./loadConfig');

  const checksum = generateSchemaChecksum(schemaContent);
  const metadata = extractSchemaMetadata(schema);

  const artifact = {
    checksum,
    generated_at: new Date().toISOString(),
    generator: options.generatorFileName || 'transformSchema.js',
    version: schema.version || '1.0.0',
    title: schema.title || 'Untitled',
    requiredFields: enumerateRequiredFields(schema),
    statuses: enumerateStatuses(schema),
    sizes: enumerateSizes(schema),
    terminalStatuses: enumerateTerminalStatuses(schema),
    sizeOrdering: getSizeOrdering(schema),
    ...metadata
  };

  // Convert JavaScript JSON to Python literals
  let pythonJson = JSON.stringify(artifact, null, 2);
  pythonJson = pythonJson.replace(/true/g, 'True').replace(/false/g, 'False').replace(/null/g, 'None');

  return `"""
Comprehensive schema artifact with all validation rules and metadata.
AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
Schema checksum: ${checksum}

This module contains all schema-derived constants, enums, and validation rules
used throughout the ETL pipeline for consistent data handling.
"""

import json
from typing import Dict, Any, List

# Raw schema data (normalized from schema.json)
SCHEMA_ARTIFACT = ${pythonJson}

# Convenience accessors
def get_required_fields() -> List[str]:
    return SCHEMA_ARTIFACT["requiredFields"]

def get_statuses() -> List[str]:
    return SCHEMA_ARTIFACT["statuses"]

def get_sizes() -> List[str]:
    return SCHEMA_ARTIFACT["sizes"]

def get_terminal_statuses() -> List[str]:
    return SCHEMA_ARTIFACT["terminalStatuses"]

def get_size_ordering() -> List[str]:
    return SCHEMA_ARTIFACT["sizeOrdering"]
`;
}

// Re-export functions from sub-modules for backward compatibility
module.exports = {
  generateStatusMapping,
  generateSizeConfig,
  generateDogTypesHeader,
  generateTypescriptDogTypes,
  generatePythonDogTypes,
  generateConfigArtifact,
  generatePythonConfigArtifact,
  generateSchemaArtifact,
  generatePythonSchemaArtifact
};
