/**
 * Schema transformation utilities.
 * Pure functions for generating artifacts from schema data.
 */

const { assertSchemaStructure, generateSchemaChecksum } = require('./loadConfig');

const DEFAULT_SIZE_ORDER = ['Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'];

/**
 * Generate status mapping ESM module content from schema.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} ESM module source code
 */
function generateStatusMapping(schema, schemaContent) {
  assertSchemaStructure(schema);

  const terminalStatuses = schema.properties.Status['x-terminal-statuses'];
  const checksum = generateSchemaChecksum(schemaContent);
  const statusEntries = schema.properties.Status.enum.map((status) => {
    const displayText = status.charAt(0) + status.slice(1).toLowerCase();
    const className = `status-${status.toLowerCase()}`;
    const isTerminal = terminalStatuses.includes(status);

    return `  '${status}': {
    text: '${displayText}',
    className: '${className}',
    isTerminal: ${isTerminal}
  }`;
  });

  return `/**
 * Shared status mapping constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 *
 * CONTRACT: Status keys MUST exactly match ETL normalized statuses from schema.
 * If you add a new normalized status in schema, regenerate this file.
 */

export const STATUS_MAPPING = {
${statusEntries.join(',\n')}
};

export function getStatusDisplay(status) {
  return STATUS_MAPPING[status] || STATUS_MAPPING['UNKNOWN'];
}

export function isTerminalStatus(status) {
  return STATUS_MAPPING[status]?.isTerminal || false;
}

/**
 * Get all valid status keys for synchronization checks.
 * Tests can use this to ensure schema and UI stay in lockstep.
 */
export function getAllStatuses() {
  return Object.keys(STATUS_MAPPING);
}

// Note: Semantic flags (isInCustody, isAvailable, isHospice) are now computed by ETL
// and stored as IsInCustody, IsAvailableForAdoption, IsHospice in the schema.
// Use dogDerived.js helpers to access these flags from the schema fields.
`;
}

/**
 * Generate size configuration ESM module content from schema.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} ESM module source code
 * @throws {Error} If size enum order doesn't match DEFAULT_SIZE_ORDER
 */
function generateSizeConfig(schema, schemaContent) {
  assertSchemaStructure(schema);

  const sizeEnum = schema.properties.Size.enum;
  if (JSON.stringify(sizeEnum) !== JSON.stringify(DEFAULT_SIZE_ORDER)) {
    throw new Error(
      `Schema Size enum order does not match expected SIZE_ORDER: ${JSON.stringify(sizeEnum)}\n` +
        `Expected: ${JSON.stringify(DEFAULT_SIZE_ORDER)}\n` +
        'Please update the schema to match the canonical size ordering.'
    );
  }

  const checksum = generateSchemaChecksum(schemaContent);
  const sizeOrder = sizeEnum.map((size) => `'${size}'`).join(', ');

  return `/**
 * Shared size configuration constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: ${checksum}
 */

export const SIZE_ORDER = [${sizeOrder}];

/**
 * Get the sort order index for a size string.
 * Returns a high index for unknown sizes to sort them last.
 */
export function getSizeSortIndex(size) {
  const index = SIZE_ORDER.indexOf(size);
  return index === -1 ? SIZE_ORDER.length : index;
}

/**
 * Assert that SIZE_ORDER matches the schema sizes for synchronization.
 * Call this during app startup in dev/test environments.
 */
export function assertSizeOrderMatchesSchema(schemaSizes) {
  if (!Array.isArray(schemaSizes)) return;
  if (schemaSizes.join('|') !== SIZE_ORDER.join('|')) {
    throw new Error(\`SIZE_ORDER out of sync with schema. Schema: [\${schemaSizes.join(', ')}], Config: [\${SIZE_ORDER.join(', ')}]\`);
  }
}

/**
 * Normalize a size string for display.
 * Returns the size if it's in SIZE_ORDER, otherwise returns 'UNKNOWN'.
 */
export function normalizeSizeForDisplay(size) {
  return SIZE_ORDER.includes(size) ? size : 'UNKNOWN';
}
`;
}

/**
 * Generate TypeScript header comment for Dog.types.ts.
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @param {object} options - Options object
 * @param {string} [options.generatorFileName='schemaArtifactsCli.js'] - Name of generator file
 * @returns {string} TypeScript comment header
 */
function generateDogTypesHeader(schemaContent, options = {}) {
  const {
    generatorFileName = 'schemaArtifactsCli.js'
  } = options;
  const checksum = generateSchemaChecksum(schemaContent);

  return `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript and ${generatorFileName}.
 * DO NOT MODIFY IT BY HAND. Instead, modify common/schemas/dog.schema.json,
 * then run json-schema-to-typescript and ${generatorFileName} to regenerate this file.
 * Schema checksum: ${checksum}
 */`;
}

/**
 * Generate Python dog types file content.
 * @param {object} schema - Parsed JSON schema object
 * @param {string} schemaContent - Raw schema file content (for checksum)
 * @returns {string} Python dataclass code
 */
function generatePythonDogTypes(schema, schemaContent) {
  assertSchemaStructure(schema);

  const checksum = generateSchemaChecksum(schemaContent);
  const lines = [];

  // Header
  lines.push('"""');
  lines.push('Dog data structure generated from common/schemas/dog.schema.json');
  lines.push('');
  lines.push(`Schema checksum: ${checksum}`);
  lines.push('AUTOGENERATED - DO NOT EDIT MANUALLY');
  lines.push('Run: node generate_schema_artifacts.js');
  lines.push('"""');
  lines.push('');
  lines.push('from dataclasses import dataclass');
  lines.push('from typing import Dict, Any, List, Optional');
  lines.push('from datetime import date');
  lines.push('');
  lines.push('');
  lines.push('@dataclass');
  lines.push('class Dog:');
  lines.push('    """Dog record matching the canonical JSON schema."""');
  lines.push('');

  const properties = schema.properties;
  const requiredFields = new Set(schema.required || []);

  // Separate required and optional fields
  const requiredProps = Object.entries(properties).filter(([name]) => requiredFields.has(name));
  const optionalProps = Object.entries(properties).filter(([name]) => !requiredFields.has(name));
  const allProps = [...requiredProps, ...optionalProps];

  // Track current group
  let currentGroup = null;
  const groupNames = {
    'identity': 'Identity',
    'api': 'API',
    'enrichment': 'Enrichment',
    'derived': 'Derived',
    'restricted': 'Restricted'
  };

  for (const [propName, propDef] of allProps) {
    // Group comments
    const propGroup = propDef['x-group'];
    if (propGroup && propGroup !== currentGroup) {
      currentGroup = propGroup;
      const groupDisplay = groupNames[propGroup] || propGroup.charAt(0).toUpperCase() + propGroup.slice(1);
      lines.push(`    # ${groupDisplay} fields`);
      lines.push('');
    }

    // Field name (sanitize for Python)
    const pythonFieldName = propName.replace(/[- ]/g, '_');

    // Type conversion
    let pythonType = jsonTypeToPythonType(propDef.type, propName);

    // Optional wrapper
    if (!requiredFields.has(propName)) {
      pythonType = `Optional[${pythonType}]`;
    }

    // Field declaration
    if (!requiredFields.has(propName)) {
      lines.push(`    ${pythonFieldName}: ${pythonType} = None`);
    } else {
      lines.push(`    ${pythonFieldName}: ${pythonType}`);
    }

    // Docstring
    if (propDef.description) {
      let description = propDef.description;
      if (description.includes('] ')) {
        description = description.split('] ')[1];
      }
      lines.push(`    """${description}"""`);
    }

    // Enum values
    if (propDef.enum) {
      const enumValues = propDef.enum.map(v => `"${v}"`).join(', ');
      lines.push(`    # Valid values: ${enumValues}`);
    }

    lines.push('');
  }

  // Add enum constants
  const statusEnum = schema.properties.Status?.enum || [];
  if (statusEnum.length > 0) {
    lines.push('');
    lines.push('# Status enum values');
    lines.push('DOG_STATUSES = [');
    for (const status of statusEnum) {
      lines.push(`    "${status}",`);
    }
    lines.push(']');
  }

  const sizeEnum = schema.properties.Size?.enum || [];
  if (sizeEnum.length > 0) {
    lines.push('');
    lines.push('# Size enum values');
    lines.push('DOG_SIZES = [');
    for (const size of sizeEnum) {
      lines.push(`    "${size}",`);
    }
    lines.push(']');
  }

  return lines.join('\n');
}

/**
 * Convert JSON Schema type to Python type hint.
 * @param {string|Array} jsonType - JSON Schema type
 * @param {string} propertyName - Property name for special handling
 * @returns {string} Python type hint
 */
function jsonTypeToPythonType(jsonType, propertyName = '') {
  const typeMapping = {
    'string': 'str',
    'number': 'float',
    'integer': 'int',
    'boolean': 'bool',
    'object': 'Dict[str, Any]',
  };

  if (Array.isArray(jsonType)) {
    const pythonTypes = jsonType.map(t => typeMapping[t] || 'Any').filter(t => t !== 'Any');
    return pythonTypes.length > 0 ? pythonTypes.join(' | ') : 'Any';
  }

  let baseType = typeMapping[jsonType] || 'Any';

  // Special handling for known fields
  switch (propertyName) {
    case 'IntakeDate':
      return 'str'; // ISO date string
    case 'Weight':
      return 'float | str'; // Can be number or string
    case 'Treatments':
      return 'List[Dict[str, Any]]';
    case 'Photos':
      return 'List[str]';
  }

  return baseType;
}

module.exports = {
  generateStatusMapping,
  generateSizeConfig,
  generateDogTypesHeader,
  generatePythonDogTypes,
  jsonTypeToPythonType
};
