/**
 * Unified config artifact for cross-language consumption.
 * AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
 * Config checksum: 256a0f9f
 *
 * This artifact contains normalized profile mappings and safety rules
 * that both JavaScript and Python code can consume without duplication.
 *
 * Business logic helpers are in configArtifactHelpers.js
 */

const CONFIG_ARTIFACT = {
  "checksum": "256a0f9f",
  "generated_at": "2025-11-18T23:22:56.680Z",
  "generator": "writers.js",
  "env_profiles": {
    "web": {
      "required": [
        "FIREBASE_API_KEY",
        "FIREBASE_AUTH_DOMAIN",
        "FIREBASE_PROJECT_ID",
        "FIREBASE_STORAGE_BUCKET",
        "FIREBASE_MESSAGING_SENDER_ID",
        "FIREBASE_APP_ID"
      ],
      "optional": []
    },
    "admin": {
      "required": [
        "FIREBASE_PROJECT_ID"
      ],
      "optional": []
    },
    "etl": {
      "required": [
        "SHELTERLUV_USER",
        "SHELTERLUV_PASS",
        "SHELTERLUV_API_KEY",
        "GCP_PROJECT",
        "DOGS_COLLECTION"
      ],
      "optional": [
        "E2E_LIVE_DB",
        "DISABLE_SECRET_MANAGER"
      ]
    },
    "dev": {
      "required": [
        "DEV_SCRIPTS_ENABLED"
      ],
      "optional": []
    }
  },
  "safe_profiles": [
    "dev",
    "staging",
    "e2e",
    "demo",
    "main"
  ],
  "roles": [
    "viewer",
    "closer",
    "staff"
  ],
  "profile_safety_map": {
    "dev": {
      "gcp_project": "dev-muttville",
      "is_safe": true
    },
    "staging": {
      "gcp_project": "staging-muttville",
      "is_safe": true
    },
    "e2e": {
      "gcp_project": "dev-muttville",
      "is_safe": true
    },
    "demo": {
      "gcp_project": "muttville-demo",
      "is_safe": true
    },
    "main": {
      "gcp_project": "muttville",
      "is_safe": true
    }
  },
  "project_safety_map": {
    "dev-muttville": {
      "is_safe": true
    },
    "staging-muttville": {
      "is_safe": true
    },
    "muttville-demo": {
      "is_safe": true
    },
    "muttville": {
      "is_safe": true
    }
  }
};

module.exports = {
  CONFIG_ARTIFACT
};
