/**
 * Unified config artifact for cross-language consumption.
 * AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
 * Config checksum: f998950e403017d1
 *
 * This artifact contains normalized profile mappings and safety rules
 * that both JavaScript and Python code can consume without duplication.
 */

const CONFIG_ARTIFACT = {
  "checksum": "f998950e403017d1",
  "generated_at": "2025-11-17T03:38:28.288Z",
  "generator": "writers.js",
  "env_profiles": {
    "web": {
      "required": [
        "FIREBASE_API_KEY",
        "FIREBASE_AUTH_DOMAIN",
        "FIREBASE_PROJECT_ID",
        "FIREBASE_STORAGE_BUCKET",
        "FIREBASE_MESSAGING_SENDER_ID",
        "FIREBASE_APP_ID"
      ],
      "optional": []
    },
    "admin": {
      "required": [
        "FIREBASE_PROJECT_ID"
      ],
      "optional": []
    },
    "etl": {
      "required": [
        "SHELTERLUV_USER",
        "SHELTERLUV_PASS",
        "SHELTERLUV_API_KEY",
        "GCP_PROJECT",
        "DOGS_COLLECTION"
      ],
      "optional": [
        "E2E_LIVE_DB",
        "DISABLE_SECRET_MANAGER"
      ]
    },
    "dev": {
      "required": [
        "DEV_SCRIPTS_ENABLED"
      ],
      "optional": []
    }
  },
  "safe_profiles": [
    "dev",
    "staging",
    "e2e",
    "demo"
  ],
  "roles": [
    "viewer",
    "closer",
    "staff"
  ],
  "profile_safety_map": {
    "dev": {
      "gcp_project": "dev-muttville",
      "is_safe": true
    },
    "staging": {
      "gcp_project": "staging-muttville",
      "is_safe": true
    },
    "e2e": {
      "gcp_project": "dev-muttville",
      "is_safe": true
    },
    "demo": {
      "gcp_project": "muttville-demo",
      "is_safe": true
    },
    "prod": {
      "gcp_project": "muttville-prod",
      "is_safe": false
    }
  },
  "project_safety_map": {
    "dev-muttville": {
      "is_safe": true
    },
    "staging-muttville": {
      "is_safe": true
    },
    "muttville-demo": {
      "is_safe": true
    },
    "muttville-prod": {
      "is_safe": false
    }
  }
};

// Convenience accessors
function getEnvProfiles() {
  return CONFIG_ARTIFACT.env_profiles;
}

function getSafeProfiles() {
  return CONFIG_ARTIFACT.safe_profiles;
}

function getRoles() {
  return CONFIG_ARTIFACT.roles;
}

function getProfileSafetyMap() {
  return CONFIG_ARTIFACT.profile_safety_map;
}

function getProjectSafetyMap() {
  return CONFIG_ARTIFACT.project_safety_map;
}

function isProfileSafe(profileName) {
  return CONFIG_ARTIFACT.profile_safety_map[profileName]?.is_safe || false;
}

function isProjectSafe(projectId) {
  return CONFIG_ARTIFACT.project_safety_map[projectId]?.is_safe || false;
}

module.exports = {
  CONFIG_ARTIFACT,
  getEnvProfiles,
  getSafeProfiles,
  getRoles,
  getProfileSafetyMap,
  getProjectSafetyMap,
  isProfileSafe,
  isProjectSafe
};
