/**
 * Comprehensive schema artifact with all validation rules and metadata.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: b976bee0
 *
 * This artifact contains all schema-derived constants, enums, and validation rules
 * used throughout the application for consistent data handling.
 */

const SCHEMA_ARTIFACT = {
  "checksum": "b976bee0",
  "generated_at": "2025-11-18T02:06:02.520Z",
  "generator": "writers.js",
  "version": "1.3.0",
  "title": "Dog",
  "requiredFields": [
    "Internal-ID",
    "ID",
    "Name",
    "Status",
    "AgeYears",
    "AgeDisplay",
    "IsInCustody",
    "IsAvailableForAdoption",
    "IsHospice",
    "IsEventDog",
    "PersonalityNotes",
    "IntakeNotes",
    "MedicalNotes"
  ],
  "statuses": [
    "AVAILABLE",
    "ADOPTED",
    "PENDING",
    "HOLD",
    "UNKNOWN"
  ],
  "sizes": [
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "UNKNOWN"
  ],
  "terminalStatuses": [
    "ADOPTED"
  ],
  "sizeOrdering": [
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "UNKNOWN"
  ],
  "fieldOwnership": {
    "Internal-ID": {
      "ownership": "api",
      "group": "identity"
    },
    "ID": {
      "ownership": "api",
      "group": "identity"
    },
    "Name": {
      "ownership": "api",
      "group": "identity"
    },
    "Breed": {
      "ownership": "api",
      "group": "api"
    },
    "AgeYears": {
      "ownership": "etl",
      "group": "derived"
    },
    "AgeDisplay": {
      "ownership": "etl",
      "group": "derived"
    },
    "Size": {
      "ownership": "api",
      "group": "api"
    },
    "Gender": {
      "ownership": "api",
      "group": "api"
    },
    "Status": {
      "ownership": "api",
      "group": "api"
    },
    "Description": {
      "ownership": "api",
      "group": "api"
    },
    "Photos": {
      "ownership": "api",
      "group": "api"
    },
    "CaseManager": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MemosRawHTML": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PersonalityNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "IntakeNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "MedicalNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "MedicalHistory": {
      "ownership": "etl",
      "group": "derived"
    },
    "AdoptionCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MedicalCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "BehaviorCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "VolunteerCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "FullAnimalProfile": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Treatments": {
      "ownership": "etl",
      "group": "derived"
    },
    "IntakeDate": {
      "ownership": "api",
      "group": "api"
    },
    "Location": {
      "ownership": "api",
      "group": "api"
    },
    "Stage": {
      "ownership": "api",
      "group": "api"
    },
    "Weight": {
      "ownership": "api",
      "group": "api"
    },
    "FosterName": {
      "ownership": "etl",
      "group": "restricted"
    },
    "FosterPhone": {
      "ownership": "etl",
      "group": "restricted"
    },
    "FosterEmail": {
      "ownership": "etl",
      "group": "restricted"
    },
    "ScrapeError": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsInCustody": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsAvailableForAdoption": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsHospice": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsEventDog": {
      "ownership": "etl",
      "group": "derived"
    },
    "Attributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "BehavioralAttributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PhysicalAttributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Species": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Color": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Pattern": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "DistinguishingMarks": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AdoptionPrice": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipNumber": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipIssuer": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipImplantDate": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AlteredBeforeArrival": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AlteredInCare": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AgeGroup": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "EstBirthdate": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "IntakeType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "IntakeSubtype": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "OutcomeType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "OutcomeSubtype": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AsilomarIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AsilomarOutcome": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "ConditionAtIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "JurisdictionIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "JurisdictionOutcome": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "RabiesTagNumber": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "EventHistory": {
      "ownership": "etl",
      "group": "derived"
    },
    "WeightHistory": {
      "ownership": "etl",
      "group": "derived"
    },
    "CategoryHistory": {
      "ownership": "etl",
      "group": "derived"
    },
    "BehavioralAssessments": {
      "ownership": "etl",
      "group": "derived"
    },
    "CompatibilityWarnings": {
      "ownership": "etl",
      "group": "derived"
    },
    "AttachedDocuments": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterId": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterIssuer": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Disclaimers": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "WebsiteMemo": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipInfo": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "RabiesTag": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "VaccinationHistory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "TreatmentsDue": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "TreatmentHistory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Diagnoses": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "DiagnosticTests": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PhysicalExams": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Procedures": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MedicalMemos": {
      "ownership": "scraper",
      "group": "enrichment"
    }
  }
};

module.exports = {
  SCHEMA_ARTIFACT
};
