/**
 * Shared size configuration constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: 2e7f82a3
 */

export const SIZE_ORDER = ['Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'];

/**
 * Get the sort order index for a size string.
 * Returns a high index for unknown sizes to sort them last.
 */
export function getSizeSortIndex(size) {
  const index = SIZE_ORDER.indexOf(size);
  return index === -1 ? SIZE_ORDER.length : index;
}

/**
 * Assert that SIZE_ORDER matches the schema sizes for synchronization.
 * Call this during app startup in dev/test environments.
 */
export function assertSizeOrderMatchesSchema(schemaSizes) {
  if (!Array.isArray(schemaSizes)) return;
  if (schemaSizes.join('|') !== SIZE_ORDER.join('|')) {
    throw new Error(`SIZE_ORDER out of sync with schema. Schema: [${schemaSizes.join(', ')}], Config: [${SIZE_ORDER.join(', ')}]`);
  }
}

/**
 * Normalize a size string for display.
 * Returns the size if it's in SIZE_ORDER, otherwise returns 'UNKNOWN'.
 */
export function normalizeSizeForDisplay(size) {
  return SIZE_ORDER.includes(size) ? size : 'UNKNOWN';
}
