/**
 * Shared size configuration constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: 9955992b
 *
 * CONTRACT: Size order MUST exactly match schema enum order.
 * If you change size enum in schema, regenerate this file.
 */

export const SIZE_ORDER = ['Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'];

export function getSizeSortIndex(size) {
  const index = SIZE_ORDER.indexOf(size);
  return index === -1 ? SIZE_ORDER.length - 1 : index; // UNKNOWN sorts last
}

export function assertSizeOrderMatchesSchema(schemaSizes) {
  const expected = SIZE_ORDER.filter(size => size !== 'UNKNOWN');
  if (JSON.stringify(expected) !== JSON.stringify(schemaSizes)) {
    throw new Error(`Size order mismatch: expected ${expected.join(', ')}, got ${schemaSizes.join(', ')}`);
  }
}

export function normalizeSizeForDisplay(size) {
  return size || 'UNKNOWN';
}
