/**
 * Shared status mapping constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: b976bee0
 *
 * CONTRACT: Status keys MUST exactly match ETL normalized statuses from schema.
 * If you add a new normalized status in schema, regenerate this file.
 */

export const STATUS_MAPPING = {
  'AVAILABLE': {
    text: 'Available',
    className: 'status-available',
    isTerminal: false
  },
  'ADOPTED': {
    text: 'Adopted',
    className: 'status-adopted',
    isTerminal: true
  },
  'PENDING': {
    text: 'Pending',
    className: 'status-pending',
    isTerminal: false
  },
  'HOLD': {
    text: 'Hold',
    className: 'status-hold',
    isTerminal: false
  },
  'UNKNOWN': {
    text: 'Unknown',
    className: 'status-unknown',
    isTerminal: false
  }
};

export function getStatusDisplay(status) {
  // Handle both old uppercase and new lowercase status formats
  const normalizedStatus = status?.toUpperCase();
  return STATUS_MAPPING[normalizedStatus] || STATUS_MAPPING['UNKNOWN'];
}

export function isTerminalStatus(status) {
  const mapping = STATUS_MAPPING[status];
  return mapping ? mapping.isTerminal : false;
}

export function getAllStatuses() {
  return Object.keys(STATUS_MAPPING);
}
