/**
 * Shared status mapping constants for ETL and frontend.
 * AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
 * Schema checksum: 65ad864d
 *
 * CONTRACT: Status keys MUST exactly match ETL normalized statuses from schema.
 * If you add a new normalized status in schema, regenerate this file.
 */

export const STATUS_MAPPING = {
  'AVAILABLE': {
    text: 'Available',
    className: 'status-available',
    isTerminal: false
  },
  'ADOPTED': {
    text: 'Adopted',
    className: 'status-adopted',
    isTerminal: true
  },
  'PENDING': {
    text: 'Pending',
    className: 'status-pending',
    isTerminal: false
  },
  'HOLD': {
    text: 'Hold',
    className: 'status-hold',
    isTerminal: false
  },
  'UNKNOWN': {
    text: 'Unknown',
    className: 'status-unknown',
    isTerminal: false
  }
};

export function getStatusDisplay(status) {
  return STATUS_MAPPING[status] || STATUS_MAPPING['UNKNOWN'];
}

export function isTerminalStatus(status) {
  return STATUS_MAPPING[status]?.isTerminal || false;
}

/**
 * Get all valid status keys for synchronization checks.
 * Tests can use this to ensure schema and UI stay in lockstep.
 */
export function getAllStatuses() {
  return Object.keys(STATUS_MAPPING);
}

// Note: Semantic flags (isInCustody, isAvailable, isHospice) are now computed by ETL
// and stored as IsInCustody, IsAvailableForAdoption, IsHospice in the schema.
// Use dogDerived.js helpers to access these flags from the schema fields.
