#!/usr/bin/env python3
"""
Generate Python type definitions from the canonical dog schema.
Creates services/etl-scraper-py/dog_types.py with typed dataclasses.

Usage:
    python3 scripts/generate_python_dog_types.py
"""

import json
import os
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from datetime import date


def load_schema() -> Dict[str, Any]:
    """Load the dog schema from the canonical location."""
    schema_path = os.path.join(os.path.dirname(__file__), '..', 'common', 'schemas', 'dog.schema.json')
    with open(schema_path, 'r') as f:
        return json.load(f)


def json_type_to_python_type(json_type: str, property_name: str = None) -> str:
    """Convert JSON Schema types to Python type hints."""
    type_mapping = {
        'string': 'str',
        'number': 'float',
        'integer': 'int',
        'boolean': 'bool',
        'object': 'Dict[str, Any]',
    }

    if isinstance(json_type, list):
        # Handle union types like ["string", "number"]
        python_types = [type_mapping.get(t, 'Any') for t in json_type if t in type_mapping]
        return ' | '.join(python_types) if python_types else 'Any'

    base_type = type_mapping.get(json_type, 'Any')

    # Special handling for known fields
    if property_name == 'IntakeDate':
        return 'str'  # ISO date string
    elif property_name == 'Weight':
        return 'float | str'  # Can be number or string
    elif property_name == 'Treatments':
        return 'List[Dict[str, Any]]'
    elif property_name == 'Photos':
        return 'List[str]'

    return base_type


def generate_dataclass(schema: Dict[str, Any]) -> str:
    """Generate the Dog dataclass from schema properties."""
    lines = []

    # Class header with schema metadata
    lines.append('"""')
    lines.append('Dog data structure generated from common/schemas/dog.schema.json')
    lines.append('')
    lines.append(f'Schema version: {schema.get("version", "unknown")}')
    lines.append('AUTOGENERATED - DO NOT EDIT MANUALLY')
    lines.append('Run: python3 scripts/generate_python_dog_types.py')
    lines.append('"""')
    lines.append('')
    lines.append('from dataclasses import dataclass')
    lines.append('from typing import Dict, Any, List, Optional')
    lines.append('from datetime import date')
    lines.append('')
    lines.append('')
    lines.append('@dataclass')
    lines.append('class Dog:')
    lines.append('    """Dog record matching the canonical JSON schema."""')
    lines.append('')

    properties = schema.get('properties', {})
    required_fields = set(schema.get('required', []))

    for prop_name, prop_def in properties.items():
        json_type = prop_def.get('type')
        python_type = json_type_to_python_type(json_type, prop_name)

        # Add Optional wrapper for non-required fields
        if prop_name not in required_fields:
            python_type = f'Optional[{python_type}]'

        # Generate field with default
        default_value = 'None' if prop_name not in required_fields else '...'
        lines.append(f'    {prop_name}: {python_type} = {default_value}')

        # Add docstring from schema description
        if 'description' in prop_def:
            description = prop_def['description']
            # Clean up the description (remove [SOURCE] prefixes for brevity)
            if '[' in description and ']' in description:
                description = description.split('] ', 1)[1] if '] ' in description else description
            lines.append(f'    """{description}"""')

        # Add enum info as comments
        if 'enum' in prop_def:
            enum_values = prop_def['enum']
            lines.append(f'    # Valid values: {", ".join(repr(v) for v in enum_values)}')

        lines.append('')

    return '\n'.join(lines)


def generate_additional_types(schema: Dict[str, Any]) -> str:
    """Generate additional type definitions if needed."""
    lines = []

    # Status enum
    status_enum = schema.get('properties', {}).get('Status', {}).get('enum', [])
    if status_enum:
        lines.append('')
        lines.append('# Status enum values')
        lines.append('DOG_STATUSES = [')
        for status in status_enum:
            lines.append(f'    "{status}",')
        lines.append(']')

    # Size enum
    size_enum = schema.get('properties', {}).get('Size', {}).get('enum', [])
    if size_enum:
        lines.append('')
        lines.append('# Size enum values')
        lines.append('DOG_SIZES = [')
        for size in size_enum:
            lines.append(f'    "{size}",')
        lines.append(']')

    # Gender enum
    gender_enum = schema.get('properties', {}).get('Gender', {}).get('enum', [])
    if gender_enum:
        lines.append('')
        lines.append('# Gender enum values')
        lines.append('DOG_GENDERS = [')
        for gender in gender_enum:
            lines.append(f'    "{gender}",')
        lines.append(']')

    return '\n'.join(lines)


def main():
    """Generate the Python types file."""
    schema = load_schema()

    # Generate the dataclass
    dataclass_code = generate_dataclass(schema)

    # Generate additional types
    additional_types = generate_additional_types(schema)

    # Combine
    full_code = dataclass_code + additional_types

    # Write to target file
    target_dir = os.path.join(os.path.dirname(__file__), '..', 'services', 'etl-scraper-py')
    target_file = os.path.join(target_dir, 'dog_types.py')

    with open(target_file, 'w') as f:
        f.write(full_code)

    print(f'Generated {target_file}')


if __name__ == '__main__':
    main()
