"""
Unified config artifact for Python consumption.
AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
Config checksum: f998950e403017d1

This module contains normalized profile mappings and safety rules
that mirror the JavaScript CONFIG_ARTIFACT for cross-language consistency.
"""

import json
from typing import Dict, Any, List

# Raw config data (normalized from config.json)
CONFIG_ARTIFACT = {
  "checksum": "f998950e403017d1",
  "generated_at": "2025-11-17T03:38:28.290Z",
  "generator": "writers.js",
  "env_profiles": {
    "web": {
      "required": [
        "FIREBASE_API_KEY",
        "FIREBASE_AUTH_DOMAIN",
        "FIREBASE_PROJECT_ID",
        "FIREBASE_STORAGE_BUCKET",
        "FIREBASE_MESSAGING_SENDER_ID",
        "FIREBASE_APP_ID"
      ],
      "optional": []
    },
    "admin": {
      "required": [
        "FIREBASE_PROJECT_ID"
      ],
      "optional": []
    },
    "etl": {
      "required": [
        "SHELTERLUV_USER",
        "SHELTERLUV_PASS",
        "SHELTERLUV_API_KEY",
        "GCP_PROJECT",
        "DOGS_COLLECTION"
      ],
      "optional": [
        "E2E_LIVE_DB",
        "DISABLE_SECRET_MANAGER"
      ]
    },
    "dev": {
      "required": [
        "DEV_SCRIPTS_ENABLED"
      ],
      "optional": []
    }
  },
  "safe_profiles": [
    "dev",
    "staging",
    "e2e",
    "demo"
  ],
  "roles": [
    "viewer",
    "closer",
    "staff"
  ],
  "profile_safety_map": {
    "dev": {
      "gcp_project": "dev-muttville",
      "is_safe": True
    },
    "staging": {
      "gcp_project": "staging-muttville",
      "is_safe": True
    },
    "e2e": {
      "gcp_project": "dev-muttville",
      "is_safe": True
    },
    "demo": {
      "gcp_project": "muttville-demo",
      "is_safe": True
    },
    "prod": {
      "gcp_project": "muttville-prod",
      "is_safe": False
    }
  },
  "project_safety_map": {
    "dev-muttville": {
      "is_safe": True
    },
    "staging-muttville": {
      "is_safe": True
    },
    "muttville-demo": {
      "is_safe": True
    },
    "muttville-prod": {
      "is_safe": False
    }
  }
}

# Convenience accessors
def get_env_profiles() -> Dict[str, Dict[str, List[str]]]:
    """Get environment variable profiles."""
    return CONFIG_ARTIFACT["env_profiles"]

def get_safe_profiles() -> List[str]:
    """Get list of safe (non-production) profile names."""
    return CONFIG_ARTIFACT["safe_profiles"]

def get_roles() -> List[str]:
    """Get list of valid user roles."""
    return CONFIG_ARTIFACT["roles"]

def get_profile_safety_map() -> Dict[str, Dict[str, Any]]:
    """Get profile -> {gcp_project, is_safe} mapping."""
    return CONFIG_ARTIFACT["profile_safety_map"]

def get_project_safety_map() -> Dict[str, Dict[str, Any]]:
    """Get project_id -> {is_safe} mapping."""
    return CONFIG_ARTIFACT["project_safety_map"]

def is_profile_safe(profile_name: str) -> bool:
    """Check if a profile name is safe for destructive operations."""
    return CONFIG_ARTIFACT["profile_safety_map"].get(profile_name, {}).get("is_safe", False)

def is_project_safe(project_id: str) -> bool:
    """Check if a GCP project ID is safe for destructive operations."""
    return CONFIG_ARTIFACT["project_safety_map"].get(project_id, {}).get("is_safe", False)
