# Python config artifact.
# AUTOGENERATED from common/config.json - DO NOT EDIT MANUALLY
# Config checksum: 256a0f9f

import json
from typing import Dict, Any

CONFIG_ARTIFACT = {
  "checksum": "256a0f9f",
  "generated_at": "2025-11-18T00:34:44.586Z",
  "generator": "writers.js",
  "env_profiles": {
    "web": {
      "required": [
        "FIREBASE_API_KEY",
        "FIREBASE_AUTH_DOMAIN",
        "FIREBASE_PROJECT_ID",
        "FIREBASE_STORAGE_BUCKET",
        "FIREBASE_MESSAGING_SENDER_ID",
        "FIREBASE_APP_ID"
      ],
      "optional": []
    },
    "admin": {
      "required": [
        "FIREBASE_PROJECT_ID"
      ],
      "optional": []
    },
    "etl": {
      "required": [
        "SHELTERLUV_USER",
        "SHELTERLUV_PASS",
        "SHELTERLUV_API_KEY",
        "GCP_PROJECT",
        "DOGS_COLLECTION"
      ],
      "optional": [
        "E2E_LIVE_DB",
        "DISABLE_SECRET_MANAGER"
      ]
    },
    "dev": {
      "required": [
        "DEV_SCRIPTS_ENABLED"
      ],
      "optional": []
    }
  },
  "safe_profiles": [
    "dev",
    "staging",
    "e2e",
    "demo",
    "main"
  ],
  "roles": [
    "viewer",
    "closer",
    "staff"
  ],
  "profile_safety_map": {
    "dev": {
      "gcp_project": "dev-muttville",
      "is_safe": True
    },
    "staging": {
      "gcp_project": "staging-muttville",
      "is_safe": True
    },
    "e2e": {
      "gcp_project": "dev-muttville",
      "is_safe": True
    },
    "demo": {
      "gcp_project": "muttville-demo",
      "is_safe": True
    },
    "main": {
      "gcp_project": "muttville",
      "is_safe": True
    }
  },
  "project_safety_map": {
    "dev-muttville": {
      "is_safe": True
    },
    "staging-muttville": {
      "is_safe": True
    },
    "muttville-demo": {
      "is_safe": True
    },
    "muttville": {
      "is_safe": True
    }
  }
}

def get_env_profiles() -> Dict[str, Any]:
    return CONFIG_ARTIFACT["env_profiles"]

def get_safe_profiles() -> list:
    return CONFIG_ARTIFACT["safe_profiles"]

def get_roles() -> list:
    return CONFIG_ARTIFACT["roles"]

def get_profile_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["profile_safety_map"]

def get_project_safety_map() -> Dict[str, Dict[str, Any]]:
    return CONFIG_ARTIFACT["project_safety_map"]

def is_profile_safe(profile_name: str) -> bool:
    return CONFIG_ARTIFACT["profile_safety_map"].get(profile_name, {}).get("is_safe", False)

def is_project_safe(project_id: str) -> bool:
    return CONFIG_ARTIFACT["project_safety_map"].get(project_id, {}).get("is_safe", False)
