# Python types for dog data.
# AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
# Schema checksum: 65ad864d

from dataclasses import dataclass
from typing import List, Optional, Dict, Any
from datetime import date

@dataclass
class Dog:
    Internal-ID: str
    ID: str
    Name: str
    Breed: str = None
    AgeYears: float
    AgeDisplay: str
    Size: Literal['Small', 'Medium', 'Large', 'X-Large', 'UNKNOWN'] = None
    Gender: Literal['Male', 'Female'] = None
    Status: Literal['AVAILABLE', 'ADOPTED', 'PENDING', 'HOLD', 'UNKNOWN']
    Description: str = None
    Photos: List[str] = None
    CaseManager: str = None
    MemosRawHTML: str = None
    PersonalityNotes: str
    IntakeNotes: str
    MedicalNotes: str
    MedicalHistory: Dict[str, Any] = None
    AdoptionCategory: str = None
    MedicalCategory: str = None
    BehaviorCategory: str = None
    VolunteerCategory: str = None
    FullAnimalProfile: str = None
    Treatments: List[Dict[str, Any]] = None
    IntakeDate: date = None
    Location: str = None
    Stage: str = None
    Weight: Union[str, float] = None
    FosterName: str = None
    FosterPhone: str = None
    FosterEmail: str = None
    ScrapeError: str = None
    IsInCustody: bool
    IsAvailableForAdoption: bool
    IsHospice: bool
    IsEventDog: bool
    Attributes: List[str] = None
    BehavioralAttributes: List[str] = None
    PhysicalAttributes: List[str] = None
    Species: str = None
    Color: str = None
    Pattern: str = None
    DistinguishingMarks: str = None
    AdoptionPrice: str = None
    MicrochipNumber: str = None
    MicrochipIssuer: str = None
    MicrochipImplantDate: str = None
    AlteredBeforeArrival: str = None
    AlteredInCare: str = None
    AgeGroup: str = None
    EstBirthdate: str = None
    IntakeType: str = None
    IntakeSubtype: str = None
    OutcomeType: str = None
    OutcomeSubtype: str = None
    AsilomarIntake: str = None
    AsilomarOutcome: str = None
    ConditionAtIntake: str = None
    JurisdictionIntake: str = None
    JurisdictionOutcome: str = None
    RabiesTagNumber: str = None
    PreviousShelterId: str = None
    PreviousShelterType: str = None
    PreviousShelterIssuer: str = None

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Dog':
        """Create a Dog instance from a dictionary."""
        return cls(**data)
