# Python types for dog data.
# AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
# Schema checksum: b976bee0

from typing import Dict, Any

# Dog type alias for type checking and IDE support
# The structure follows the JSON schema in common/schemas/dog.schema.json
Dog = Dict[str, Any]
