# Python types for dog data.
# AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
# Schema checksum: 65ad864d

from typing import Dict, Any

# NOTE:
#   Dog is intentionally defined as a generic mapping. The canonical
#   contract for fields, types, and required properties lives in
#   common/schemas/dog.schema.json.
#
#   Runtime code should continue to validate payloads against the JSON
#   Schema; this alias exists only to aid basic type checking.

Dog = Dict[str, Any]
