"""
Comprehensive schema artifact with all validation rules and metadata.
AUTOGENERATED from common/schemas/dog.schema.json - DO NOT EDIT MANUALLY
Schema checksum: ef20fcd3274debb3

This module contains all schema-derived constants, enums, and validation rules
used throughout the ETL pipeline for consistent data handling.
"""

import json
from typing import Dict, Any, List

# Raw schema data (normalized from schema.json)
SCHEMA_ARTIFACT = {
  "checksum": "ef20fcd3274debb3",
  "generated_at": "2025-11-17T03:38:28.290Z",
  "generator": "writers.js",
  "version": "1.3.0",
  "title": "Dog",
  "requiredFields": [
    "Internal-ID",
    "ID",
    "Name",
    "Status",
    "AgeYears",
    "AgeDisplay",
    "IsInCustody",
    "IsAvailableForAdoption",
    "IsHospice",
    "IsEventDog",
    "PersonalityNotes",
    "IntakeNotes",
    "MedicalNotes"
  ],
  "statuses": [
    "AVAILABLE",
    "ADOPTED",
    "PENDING",
    "HOLD",
    "UNKNOWN"
  ],
  "sizes": [
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "UNKNOWN"
  ],
  "terminalStatuses": [
    "ADOPTED"
  ],
  "sizeOrdering": [
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "UNKNOWN"
  ],
  "fieldOwnership": {
    "Internal-ID": {
      "ownership": "api",
      "group": "identity"
    },
    "ID": {
      "ownership": "api",
      "group": "identity"
    },
    "Name": {
      "ownership": "api",
      "group": "identity"
    },
    "Breed": {
      "ownership": "api",
      "group": "api"
    },
    "AgeYears": {
      "ownership": "etl",
      "group": "derived"
    },
    "AgeDisplay": {
      "ownership": "etl",
      "group": "derived"
    },
    "Size": {
      "ownership": "api",
      "group": "api"
    },
    "Gender": {
      "ownership": "api",
      "group": "api"
    },
    "Status": {
      "ownership": "api",
      "group": "api"
    },
    "Description": {
      "ownership": "api",
      "group": "api"
    },
    "Photos": {
      "ownership": "api",
      "group": "api"
    },
    "CaseManager": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MemosRawHTML": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PersonalityNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "IntakeNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "MedicalNotes": {
      "ownership": "etl",
      "group": "derived"
    },
    "MedicalHistory": {
      "ownership": "etl",
      "group": "derived"
    },
    "AdoptionCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MedicalCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "BehaviorCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "VolunteerCategory": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "FullAnimalProfile": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Treatments": {
      "ownership": "etl",
      "group": "derived"
    },
    "IntakeDate": {
      "ownership": "api",
      "group": "api"
    },
    "Location": {
      "ownership": "api",
      "group": "api"
    },
    "Stage": {
      "ownership": "api",
      "group": "api"
    },
    "Weight": {
      "ownership": "api",
      "group": "api"
    },
    "FosterName": {
      "ownership": "etl",
      "group": "restricted"
    },
    "FosterPhone": {
      "ownership": "etl",
      "group": "restricted"
    },
    "FosterEmail": {
      "ownership": "etl",
      "group": "restricted"
    },
    "ScrapeError": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsInCustody": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsAvailableForAdoption": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsHospice": {
      "ownership": "etl",
      "group": "derived"
    },
    "IsEventDog": {
      "ownership": "etl",
      "group": "derived"
    },
    "Attributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "BehavioralAttributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PhysicalAttributes": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Species": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Color": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "Pattern": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "DistinguishingMarks": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AdoptionPrice": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipNumber": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipIssuer": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "MicrochipImplantDate": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AlteredBeforeArrival": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AlteredInCare": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AgeGroup": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "EstBirthdate": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "IntakeType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "IntakeSubtype": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "OutcomeType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "OutcomeSubtype": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AsilomarIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "AsilomarOutcome": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "ConditionAtIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "JurisdictionIntake": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "JurisdictionOutcome": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "RabiesTagNumber": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterId": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterType": {
      "ownership": "scraper",
      "group": "enrichment"
    },
    "PreviousShelterIssuer": {
      "ownership": "scraper",
      "group": "enrichment"
    }
  }
}

# Convenience accessors for commonly used values
def get_required_fields() -> List[str]:
    """Get list of required field names."""
    return SCHEMA_ARTIFACT["requiredFields"]

def get_statuses() -> List[str]:
    """Get list of valid status values."""
    return SCHEMA_ARTIFACT["statuses"]

def get_sizes() -> List[str]:
    """Get list of valid size values."""
    return SCHEMA_ARTIFACT["sizes"]

def get_terminal_statuses() -> List[str]:
    """Get list of terminal status values."""
    return SCHEMA_ARTIFACT["terminalStatuses"]

def get_size_ordering() -> List[str]:
    """Get canonical size ordering."""
    return SCHEMA_ARTIFACT["sizeOrdering"]

def get_field_ownership() -> Dict[str, Dict[str, str]]:
    """Get field ownership metadata."""
    return SCHEMA_ARTIFACT["fieldOwnership"]

def is_required_field(field_name: str) -> bool:
    """Check if a field is required."""
    return field_name in SCHEMA_ARTIFACT["requiredFields"]

def is_terminal_status(status: str) -> bool:
    """Check if a status is terminal."""
    return status in SCHEMA_ARTIFACT["terminalStatuses"]

def get_field_ownership_info(field_name: str) -> Dict[str, str]:
    """Get ownership info for a field."""
    return SCHEMA_ARTIFACT["fieldOwnership"].get(field_name, {"ownership": "unknown", "group": "unknown"})
